name: sample worlflow

on: 
  push:
    branches: [ qa , prod]
  pull_request:
    branches: [ qa, prod ]

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: chechout 
      run: echo "Hello JOB"
      
